Concrete type for field of DequeIterator
JuliaCollections/DataStructures.jl pull request #674
Opened 2020-09-03 10:54 UTC by blegat

2020-09-04 16:33 UTC, eulerkochy approved these changes

2020-12-16 13:09 UTC, blegat commented
Anything blocking this PR to be merged ?

2020-12-16 14:04 UTC, eulerkochy requested changes
can you please add a trivial test for type-checking `q` ?

2020-12-16 14:04 UTC, eulerkochy commented
@blegat I forget to submit the review. Sorry for holding this up.

2020-12-16 14:25 UTC, blegat commented
It was done in https://github.com/JuliaCollections/DataStructures.jl/pull/689

2020-12-16 14:25 UTC, closed without merging